version: "3.9"

services:
  surveybasket:
    container_name: surveybasket-app
    image: khaledzaabat/survey_basket:1.0
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - JwtSettings__Issuer=SurveyBasketAuthServer
      - JwtSettings__Audience=SurveyBasketClient
      - JwtSettings__SecretKey=${JwtSettings__SecretKey}
      - ConnectionStrings__PostgreSql=${ConnectionStrings__PostgreSql}
      - ConnectionStrings__HangfireConnection=${ConnectionStrings__HangfireConnection}
      - HangfireSettings__Username=${HangfireSettings__Username}
      - HangfireSettings__Password=${HangfireSettings__Password}
      - MailSettings__Password=${MailSettings__Password}
      - Admin__Password=${Admin__Password}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
    networks:
      - surveybasket-net

  redis:
    container_name: surveybasket-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - surveybasket-net

  ops-seq:
    image: datalust/seq:latest
    container_name: ops-seq
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_PASSWORD}
    networks:
      - surveybasket-net
    ports:
       - 5341:5341   # Serilog sends logs here
       - 8081:80     # Seq dashboard web UI

networks:
  surveybasket-net:
    driver: bridge

volumes:
  seq_data:
