version: "3.9"

services:
  surveybasket:
    container_name: surveybasket-app
    image: khaledzaabat/survey_basket:1.0
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=SurveyBasket;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379
      - JwtSettings__Issuer=SurveyBasketAuthServer
      - JwtSettings__Audience=SurveyBasketClient
      - JwtSettings__SecretKey=${JWT_SECRET}
    depends_on:
      - sqlserver
      - redis
    networks:
      - surveybasket-net

  sqlserver:
    container_name: surveybasket-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - surveybasket-net

  redis:
    container_name: surveybasket-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - surveybasket-net
  ops.seq:
    image: datalust/seq:latest
    container_name: Ops.Seq
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
      - surveybasket-net
    ports:
      - 5341:5341
      - 8081:80


networks:
  surveybasket-net:
    driver: bridge

volumes:
  sql_data:
  seq_data:
