@SurveyBasket_HostAddress = https://localhost:7240

POST {{SurveyBasket_HostAddress}}/Auth/register
{
  "email": "john.doe@example.com",
  "password": "AnotherPass123!",
  "firstName": "John",
  "lastName": "Doe"
  
}
